sonar.projectKey=antliadev_jiradashofc
sonar.organization=antliadev
sonar.projectName=JiraDash Oficial
sonar.sources=src,server,lib,api
sonar.tests=tests
sonar.exclusions=dist/**,node_modules/**,coverage/**,public/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
